import type { User, Listing } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

// Mock users removed in favor of real DB auth.

export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    title: '2022 Scania R 450',
    category: 'Truck',
    brand: 'Scania',
    model: 'R 450',
    year: 2022,
    condition: 'Excellent',
    country: 'Germany',
    city: 'Berlin',
    description: 'Almost new Scania R 450 with low mileage. Used for light-duty transport within the city. Maintained by certified mechanics. All service records available. No accidents, clean title.',
    specs: [
      { key: 'Mileage', value: '50,000 km' },
      { key: 'Engine', value: 'DC13 156' },
      { key: 'Power', value: '450 HP' },
      { key: 'Gearbox', value: 'Opticruise' },
    ],
    visibility: 'public',
    createdAt: new Date('2023-10-01').toISOString(),
    media: [
      { id: 'img1', url: getImage('truck-1')?.imageUrl!, imageHint: getImage('truck-1')?.imageHint!, sortOrder: 1 },
      { id: 'img2', url: getImage('truck-interior-1')?.imageUrl!, imageHint: getImage('truck-interior-1')?.imageHint!, sortOrder: 2 },
      { id: 'img3', url: getImage('truck-engine-1')?.imageUrl!, imageHint: getImage('truck-engine-1')?.imageHint!, sortOrder: 3 },
    ],
    extraNotes: 'Available for inspection on weekdays. Price negotiable for serious buyers. Financing options available through our partners.',
    verificationStatus: 'Verified',
    documents: [
      { id: 'doc-1', name: 'Service History.pdf', type: 'Maintenance', url: '#', createdAt: new Date().toISOString() },
      { id: 'doc-2', name: 'Registration.pdf', type: 'Registration', url: '#', createdAt: new Date().toISOString() },
    ],
    internalNotes: [
      { id: 'note-1', note: 'Supplier is very reliable. Fast paperwork.', authorId: 'user-1', createdAt: new Date().toISOString() }
    ],
    availabilityStatus: 'available',
    type: 'single',
    quantity: 1,
  },
  {
    id: 'listing-2',
    title: '2019 Volvo FH 500',
    category: 'Truck',
    brand: 'Volvo',
    model: 'FH 500',
    year: 2019,
    condition: 'Good',
    country: 'Netherlands',
    city: 'Rotterdam',
    description: 'Well-maintained Volvo FH 500, single owner, used for long-haul routes across Europe. Reliable and fuel-efficient. Regular services performed at Volvo service centers.',
    specs: [
      { key: 'Mileage', value: '320,000 km' },
      { key: 'Engine', value: 'D13K500' },
      { key: 'Power', value: '500 HP' },
      { key: 'Cabin', value: 'Globetrotter XL' },
    ],
    visibility: 'public',
    createdAt: new Date('2023-09-15').toISOString(),
    media: [
      { id: 'img4', url: getImage('truck-2')?.imageUrl!, imageHint: getImage('truck-2')?.imageHint!, sortOrder: 1 },
    ],
    extraNotes: 'Tires replaced 6 months ago. Minor cosmetic wear on the driver side door. Full documentation available for members.',
    verificationStatus: 'Pending',
    documents: [],
    internalNotes: [],
    availabilityStatus: 'expected',
    type: 'single',
    quantity: 1,
  },
  {
    id: 'listing-3',
    title: 'Komatsu PC210 Excavator',
    category: 'Heavy Equipment',
    brand: 'Komatsu',
    model: 'PC210',
    year: 2020,
    condition: 'Good',
    country: 'USA',
    city: 'Houston, TX',
    description: 'Komatsu PC210 excavator with standard bucket. Used in residential construction projects. Low operating hours for its age.',
    specs: [
      { key: 'Hours', value: '2,500' },
      { key: 'Weight', value: '22 tons' },
      { key: 'Engine', value: 'Komatsu SAA6D107E-1' },
      { key: 'Condition', value: 'Good' },
    ],
    visibility: 'public',
    createdAt: new Date('2023-11-05').toISOString(),
    media: [
      { id: 'img5', url: getImage('equipment-1')?.imageUrl!, imageHint: getImage('equipment-1')?.imageHint!, sortOrder: 1 },
    ],
    extraNotes: 'Hydraulics recently serviced. Available for immediate pickup.',
    verificationStatus: 'Unverified',
    documents: [
      { id: 'doc-3', name: 'Inspection Report Q3.pdf', type: 'Inspection', url: '#', createdAt: new Date().toISOString() }
    ],
    internalNotes: [],
    availabilityStatus: 'available',
    type: 'single',
    quantity: 1,
  },
  {
    id: 'listing-4',
    title: 'Schmitz Cargobull Flatbed Trailer',
    category: 'Trailer',
    brand: 'Schmitz Cargobull',
    year: 2021,
    condition: 'Excellent',
    country: 'Poland',
    city: 'Warsaw',
    description: 'Like new Schmitz Cargobull flatbed trailer. Minimal use, stored indoors. Perfect for various cargo types.',
    specs: [
      { key: 'Length', value: '13.6 m' },
      { key: 'Axles', value: '3' },
      { key: 'Payload', value: '27,000 kg' },
    ],
    visibility: 'public',
    createdAt: new Date('2023-10-20').toISOString(),
    media: [
      { id: 'img6', url: getImage('trailer-1')?.imageUrl!, imageHint: getImage('trailer-1')?.imageHint!, sortOrder: 1 },
    ],
    extraNotes: 'Inspection reports available upon request for members.',
    verificationStatus: 'Verified',
    documents: [],
    internalNotes: [],
    availabilityStatus: 'reserved',
    type: 'single',
    quantity: 1,
  },
  {
    id: 'listing-5',
    title: 'Caterpillar D6 Bulldozer',
    category: 'Heavy Equipment',
    brand: 'Caterpillar',
    model: 'D6',
    year: 2018,
    condition: 'Used',
    country: 'Canada',
    city: 'Calgary',
    description: 'CAT D6 bulldozer, fully operational. Has seen significant use in mining operations but has been professionally maintained. Strong and reliable machine.',
    specs: [
      { key: 'Hours', value: '8,200' },
      { key: 'Blade', value: 'SU Blade' },
      { key: 'Undercarriage', value: '50% life remaining' },
    ],
    visibility: 'members',
    createdAt: new Date('2023-08-01').toISOString(),
    media: [
      { id: 'img7', url: getImage('equipment-2')?.imageUrl!, imageHint: getImage('equipment-2')?.imageHint!, sortOrder: 1 },
    ],
    extraNotes: 'This listing is only visible to logged-in members. Full maintenance logs are attached as documents.',
    verificationStatus: 'Verified',
    documents: [
      { id: 'doc-4', name: 'Maintenance Log.csv', type: 'Maintenance', url: '#', createdAt: new Date().toISOString() }
    ],
    internalNotes: [
      { id: 'note-2', note: 'This is a high-demand item, price is firm.', authorId: 'user-1', createdAt: new Date().toISOString() }
    ],
    availabilityStatus: 'available',
    type: 'single',
    quantity: 1,
  },
  // LOTS
  {
    id: 'listing-lot-1',
    title: 'Fleet Renewal: 10x Scania R 450',
    category: 'Truck',
    brand: 'Scania',
    model: 'R 450',
    year: 2018,
    condition: 'Good',
    country: 'Spain',
    city: 'Madrid',
    description: 'Bulk offer for 10 identical scania units. Well maintained fleet, all service records available. Ideal for export or fleet expansion.',
    specs: [
      { key: 'Total Units', value: '10' },
      { key: 'Avg Mileage', value: '450,000 km' },
      { key: 'Engine', value: 'DC13' },
    ],
    visibility: 'public',
    createdAt: new Date().toISOString(),
    media: [
      { id: 'img-lot-1', url: getImage('truck-1')?.imageUrl!, imageHint: getImage('truck-1')?.imageHint!, sortOrder: 1 },
    ],
    verificationStatus: 'Verified',
    documents: [],
    internalNotes: [],
    availabilityStatus: 'available',
    type: 'lot',
    quantity: 10,
    pricePerUnit: 25000,
    isFleetSeller: true,
    isExportReady: true,
  },
  {
    id: 'listing-lot-2',
    title: 'Export Pack: 50x Krone Mega Liner',
    category: 'Trailer',
    brand: 'Krone',
    year: 2015,
    condition: 'Used',
    country: 'Germany',
    city: 'Hamburg',
    description: 'Large batch of curtain siders available immediately. Export documents ready. Bulk discount applied.',
    specs: [
      { key: 'Total Units', value: '50' },
      { key: 'Axles', value: '3' },
      { key: 'Type', value: 'Mega Liner' },
    ],
    visibility: 'public',
    createdAt: new Date().toISOString(),
    media: [
      { id: 'img-lot-2', url: getImage('trailer-1')?.imageUrl!, imageHint: getImage('trailer-1')?.imageHint!, sortOrder: 1 },
    ],
    verificationStatus: 'Verified',
    documents: [],
    internalNotes: [],
    availabilityStatus: 'expected',
    type: 'lot',
    quantity: 50,
    pricePerUnit: 8000,
    isFleetSeller: true,
    isExportReady: true,
  }
];
